"""create_database

Revision ID: b6f91ed08716
Revises: 9bffda38f1f6
Create Date: 2021-07-21 10:11:45.853898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f91ed08716'
down_revision = '9bffda38f1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('typea', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_user_typea'), 'user', ['typea'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_typea'), table_name='user')
    op.drop_column('user', 'typea')
    # ### end Alembic commands ###
